import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { fetchHero } from "@/lib/fetchHero";

export default function Home({ heroData }) {
  return (
    <>
      <Head>
        <title>Andrés Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>{heroData.role} </h1>
        {heroData.greeting.map((heroData, index) => (
            <h3 key={index}>{heroData}</h3>
          ))}
      </main>
    </>
  );
}

export const getStaticProps = async () => {
  const heroData = await fetchHero();

  return {
    props: {
      heroData,
    },
  };
};
