import Head from "next/head";
import { fetchHero } from "@/lib/fetchHero";
import Hero from "@/components/Hero";

export default function Home({ heroData }) {
  return (
    <>
      <Head>
        <title>Andrés Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        <section id="hero">
          <Hero data={heroData}/>
        </section>
      </main>
    </>
  );
}

export const getStaticProps = async () => {
  const heroData = await fetchHero();

  return {
    props: {
      heroData,
    },
  };
};
