import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { fetchMessage } from "@/lib/fetchMessage";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ message }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Message from Api: </h1>
        <h2>{message}</h2>
      </main>
    </>
  );
}

export const getStaticProps = async () => {
  const message = await fetchMessage();

  return {
    props: {
      message,
    },
  };
};
